# Cloud Build configuration for CodeMentor backend
# Triggered on push to main branch

steps:
  # Step 1: Run tests
  - name: 'python:3.11'
    id: 'test'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd backend
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        pytest tests/ -v --cov=src

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/codementor-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/codementor-backend:latest'
      - '-f'
      - 'backend/Dockerfile'
      - '.'

  # Step 3: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/codementor-backend'

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'codementor-backend'
      - '--image=gcr.io/$PROJECT_ID/codementor-backend:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--vpc-connector=codementor-connector'
      - '--set-secrets=DATABASE_URL=database-url:latest,REDIS_URL=redis-url:latest'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--max-instances=10'
      - '--min-instances=0'
      - '--timeout=300'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/codementor-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/codementor-backend:latest'

# Build timeout
timeout: '1200s'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'
